### ISSUE TITLE
Firecloud access to data via DOS

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/administration#32]

**Comment by david4096** [comment]
The DOS service allows one to resolve identifiers to a list of URLs. A first pass at this will present data in GCS via dos-dss-lambda. This will allow DOS identifiers in manifests to be resolved to cloud storage locations.

**Comment by briandoconnor** [comment]
Adding a discussion we had over email.

Hi,

So I thought the conversation on DOS + Auth was getting muddled on the call.  Different people were coming at it from different perspectives I think DOS and FireCloud's interaction will evolve over time.  I think what we want to do is something really simple initially, let's just start with this hypothetical flow:

1) you have a DOS URL that you get from a faceted browser (Boardwalk or Gen3 Framework services portal or maybe another browser from Xe,Ar,He?)

dos://storage.ucsc.edu/ga4gh/dos/v1/dataobjects/{data_object_id}/versions/{version}

2) you can pass that URL into your workspace creation in FireCloud just as you do now with a gs:// URL.

3) you can parameterize a WDL workflow with this URL and trigger the running of the workflow in FireCloud on the Google cloud

4) at runtime, FireCloud understands this is a DOS URL, gets the URL which returns something that looks like this:

{
  "data_objects": [
    {
      "id": "UUID",
      "name": "file.bam",
      "size": "128219",
      "created": "2018-02-07T17:11:38.475Z",
      "updated": "2018-02-07T17:11:38.475Z",
      "version": "1.7",
      "mime_type": "binary",
      "checksums": [
        {
          "checksum": "sha256",
          "type": "sldfjslkdjfklsdj"
        }
      ],
      "urls": [
        {
          "url": "gs://bucket-that-we-share-access-to/file-path...",
          "system_metadata": { ... } 
        } ]
   ...
}

And this allows FireCloud to get a gs URL for a file in the shared requestor pays bucket that we all have access to for TOPMed data.

No auth token needed here since it's returning a shared gs path that isn't public but shared between all our systems.  We all have access to it including the user running the workflow in FireCloud.

So that's our safe harbor, something to start with.  And this process works with FireCloud whether the service is Indexd or HCA (or another full stack's storage system on Google)

A future iteration would take a bearer token (details of how the bearer token is created for a given system like HCA or Indexd and whether or not this token is the same used by Google cloud and FireCloud or if it's storage system specific is TBD).  By passing in a valid token it establishes the user identity and their authorization, and, if the user is authorized, the storage system underlying DOS would create a signed URL and/or provide the gs path along with temporary credentials for accessing that path.

This future iteration requires the auth group's work and will be informed by it.  But I don't want to get hung up on this right now since we can do our 6 month demo simply by all sharing access to the same bucket and using DOS as our GUID -> concrete google storage path service.

Does this gel with everyone's understanding?  Concerns? Thoughts?
