### ISSUE TITLE
WDL/CWL versions of the TOPMed pipelines

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/administration#4]
* Brian to send around specs for the pipeline and ping groups
* Kristian will give a contact at Broad for WDL version and UCSC/Chicago for CWL version

**Comment by briandoconnor** [comment]
https://github.com/BD2KGenomics/toil-topmed

**Comment by briandoconnor** [comment]
Hey,

Just wanted to followup on getting the ball rolling for producing a WDL and CWL version of the basic, TOPMed alignment workflow.  

See https://github.com/DataBiosphere/administration/issues/4

Specifically, from that ticket:

This is the Toil version of the pipeline created by Trevor at UCSC:
https://github.com/BD2KGenomics/toil-topmed

This is based on the spec that Goncalo provided for their TOPMed alignment pipeline which can be found here:

https://github.com/CCDG/Pipeline-Standardization/blob/master/PipelineStandard.md

Is there a person at the Broad that can help with making the WDL version of this workflow?

Is there a person at U. Chicago that can help with making the CWL version of this workflow?

Thanks

Brian

**Comment by ruchim** [comment]
Hey Brian, is it possible to use GATK4 for the BQSR step as it's optimized for the cloud and enables the usage of NIO streaming. This is beneficial as it should help make the pipeline faster and cheaper.

**Comment by kcibul** [comment]
@ruchim  -- are the scientific outputs of the old BQSR and the GATK4 BQSR equivalent? (maybe a question for E. Banks)

**Comment by briandoconnor** [comment]
* Eric and Ruchi - WDL version 
* Christina will comment on the CWL version
* let's put this in our datbiosphere org

**Comment by david4096** [comment]
As Broad folks are actually writing the WDL this may be less than useful, but for your perusal @dailydreaming put this WDL stub together https://gist.github.com/david4096/ae5d367c15c23325f06b461dcdf5bfc4

The Python Toil version of this workflow can be seen here https://github.com/BD2KGenomics/toil-topmed

**Comment by eitanbanks** [comment]
BQSR in GATK4 is actually better.  They are both functionally equivalent (and adhere to the pipeline standardization), but they are not exactly the same.  IMO we should all use GATK4.

Also, FYI, the python script used by Toil does not adhere to the pipeline standardization specification.  Base recalibration is not supposed to maintain the original quality scores, but the python script has it doing that.

**Comment by DailyDreaming** [comment]
The Toil TopMed workflow that David linked is about a year old now and
would of course need revising.  I passed him the WDL stub for what it was
worth, since I had got about an hour into it and someone told me to drop
it.  Neither of these are intended to be finished products or intended for
consumption currently.

I agree we should all use GATK4.

**Comment by DailyDreaming** [comment]
@ Eric Banks,

I'm curious, after going through the best practices here:
https://github.com/CCDG/Pipeline-Standardization/blob/master/PipelineStandard.md
 it says the `--useOriginalQualities` command for `GATK BaseRecalibrator`
is optional.  The documentation says though: "This flag tells GATK to use
the original base qualities (that were in the data before
BQSR/recalibration) which are stored in the OQ tag, if they are present,
rather than use the post-recalibration quality scores. If no OQ tag is
present for a read, the standard qual score will be used."

Which makes it seem like it obviates what `GATK BaseRecalibrator` just
did?  Which I'm assuming is what you're referring to?  Since it is listed
as optional under the standards however, maybe I am misunderstanding this.
Could you perhaps elucidate?

On Wed, Jan 17, 2018 at 1:35 PM, Lon Blauvelt <lblauvel@ucsc.edu> wrote:
>
> The Toil TopMed workflow that David linked is about a year old now and
would of course need revising.  I passed him the WDL stub for what it was
worth, since I had got about an hour into it and someone told me to drop
it.  Neither of these are intended to be finished products or intended for
consumption currently.
>
> I agree we should all use GATK4.
>
> On Wed, Jan 17, 2018 at 8:37 AM, Eric Banks <notifications@github.com>
wrote:
>>
>> BQSR in GATK4 is actually better. They are both functionally equivalent
(and adhere to the pipeline standardization), but they are not exactly the
same. IMO we should all use GATK4.
>>
>> Also, FYI, the python script used by Toil does not adhere to the
pipeline standardization specification. Base recalibration is not supposed
to maintain the original quality scores, but the python script has it doing
that.

**Comment by eitanbanks** [comment]
Sure thing.  **Using** the original qualities is different than **producing** them.  I.e. if we are re-processing an older BAM that already has the original qualities then we can optionally use them.  But if you look under the "File format" section you'll see that it explicitly calls out not maintaining the original qualities in any new CRAMs that we produce with this pipeline.

**Comment by DailyDreaming** [comment]
If that is the difference, then simply deleting the `–emit_original_quals`
flag at the end of the workflow should make it compliant?  Thanks btw, this
is my first time attempting to run this workflow.

On Wed, Jan 17, 2018 at 7:32 PM, Eric Banks <notifications@github.com>
wrote:
>
> Sure thing. Using the original qualities is different than producing
them. I.e. if we are re-processing an older BAM that already has the
original qualities then we can optionally use them. But if you look under
the "File format" section you'll see that it explicitly calls out not
maintaining the original qualities in any new CRAMs that we produce with
this pipeline.

**Comment by eitanbanks** [comment]
Yes!  I think that's all you'd need to do to make it meet the spec.
I didn't look super closely at the entire workflow, but nothing else stood out to me as not looking right.

**Comment by ruchim** [comment]
@briandoconnor Where should we add the WDL workflow, which repo? Thanks!

**Comment by wshands** [comment]
Hi @ruchim would you please put the the WDL workflow here: https://github.com/DataBiosphere/topmed-workflows
Thanks!

**Comment by cricketsloan** [comment]
This is subsumed by Datasphere/andinistration#31
